ignore:
  - .github
  - api/v1alpha1/generated.pb.go
  - api/v1alpha1/zz_generated.deepcopy.go
  - bin
  - config
  - docs
  - test
  - examples
  - hack
  - kill
  - manager
  - runner
  - runtimes
  - shared/containerkiller
  - shared/podexec
  - shared/util/error.go
  - shared/util/io.go
coverage:
  status:
    # we've found this not to be useful
    patch: off
    project:
      default:
        # allow test coverage to drop by 2%, assume that it's typically due to CI problems
        threshold: 2