namespace: argo-dataflow-system
resources:
  - github.com/argoproj/argo-workflows/manifests/base/argo-server?ref=dev-dataflow
  - argo-server-role.yaml
  - argo-server-rolebinding.yaml
patchesStrategicMerge:
  - argo-server-deploy.yaml
