namespace: argo-dataflow-system
resources:
  - github.com/argoproj/argo-workflows/manifests/base/argo-server
  - argo-server-role.yaml
  - argo-server-rolebinding.yaml
patchesStrategicMerge:
  - argo-server-deploy.yaml
