apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named S3 configuration.

      The secret must be named `dataflow-s3-${name}`.
      [Learn about configuration](../docs/CONFIGURATION.md)
  name: dataflow-s3-default
  namespace: argo-dataflow-system
stringData:
  accessKeyId: admin
  credentials.accessKeyId.key: accessKeyId
  credentials.accessKeyId.name: dataflow-s3-default
  credentials.secretAccessKey.key: secretAccessKey
  credentials.secretAccessKey.name: dataflow-s3-default
  endpoint.url: http://minio:9000
  region: us-west-2
  secretAccessKey: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: argo-dataflow-system
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minio
  name: minio
  namespace: argo-dataflow-system
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - command:
        - minio
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: admin
        - name: MINIO_SECRET_KEY
          value: password
        image: minio/minio:RELEASE.2019-12-17T23-16-33Z
        lifecycle:
          postStart:
            exec:
              command:
              - mkdir
              - -p
              - /data/my-bucket
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        name: main
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
