apiVersion: v1
kind: Secret
metadata:
  name: mysql-data-source
  namespace: argo-dataflow-system
stringData:
  dataSource: root:password@tcp(mysql)/test
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: argo-dataflow-system
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: argo-dataflow-system
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: test
        image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
