apiVersion: v1
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222
    authorization {
      token: "testingtokentestingtoken"
    }
kind: ConfigMap
metadata:
  name: nats-config
  namespace: argo-dataflow-system
---
apiVersion: v1
data:
  stan.conf: |
    port: 4222
    http: 8222
    authorization {
      token: "testingtokentestingtoken"
    }

    streaming {
     ns: "nats://nats:4222"
     id: stan
     store: file
     dir: /data/stan/store
    }
kind: ConfigMap
metadata:
  name: stan-config
  namespace: argo-dataflow-system
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named Kafka configuration.

      The secret must be named `dataflow-kafka-${name}`.

      # Brokers as a comma-separated list
      brokers: broker.a,broker.b
      # Kafka version
      version: "2.0.0"

      # Enable TLS
      net.tls.caCert: ""
      net.tls.cert: ""
      net.tls.key: ""

      # Enable SASL
      net.sasl.mechanism: PLAIN
      net.sasl.user: ""
      net.sasl.password: ""

      [Learn about configuration](../docs/CONFIGURATION.md)
  name: dataflow-kafka-default
  namespace: argo-dataflow-system
stringData:
  brokers: kafka-broker:9092
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named S3 configuration.

      The secret must be named `dataflow-s3-${name}`.
      [Learn about configuration](../docs/CONFIGURATION.md)
  name: dataflow-s3-default
  namespace: argo-dataflow-system
stringData:
  accessKeyId: admin
  credentials.accessKeyId.key: accessKeyId
  credentials.accessKeyId.name: dataflow-s3-default
  credentials.secretAccessKey.key: secretAccessKey
  credentials.secretAccessKey.name: dataflow-s3-default
  endpoint.url: http://minio:9000
  region: us-west-2
  secretAccessKey: password
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named NATS Streaming configuration.

      The secret must be named `dataflow-nats-${name}`.

      [Learn about configuration](../docs/CONFIGURATION.md)
  name: dataflow-stan-default
  namespace: argo-dataflow-system
stringData:
  authToken: testingtokentestingtoken
  clusterId: stan
  maxInflight: "15"
  natsMonitoringUrl: http://stan:8222
  natsUrl: nats
  subjectPrefix: NamespacedPipelineName
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-data-source
  namespace: argo-dataflow-system
stringData:
  dataSource: root:password@tcp(mysql)/test
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: argo-dataflow-system
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: argo-dataflow-system
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: argo-dataflow-system
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats
  name: nats
  namespace: argo-dataflow-system
spec:
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
  - name: leafnodes
    port: 7422
  - name: gateways
    port: 7522
  selector:
    app: nats
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stan
  name: stan
  namespace: argo-dataflow-system
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 7777
  - name: monitor
    port: 8222
  selector:
    app: stan
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: argo-dataflow-system
spec:
  ports:
  - name: client
    port: 2181
  - name: follower
    port: 2888
  - name: leader
    port: 3888
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: argo-dataflow-system
spec:
  selector:
    matchLabels:
      app: kafka-broker
  serviceName: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-broker
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 9092
        readinessProbe:
          tcpSocket:
            port: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minio
  name: minio
  namespace: argo-dataflow-system
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - command:
        - minio
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: admin
        - name: MINIO_SECRET_KEY
          value: password
        image: minio/minio:RELEASE.2019-12-17T23-16-33Z
        lifecycle:
          postStart:
            exec:
              command:
              - mkdir
              - -p
              - /data/my-bucket
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        name: main
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: argo-dataflow-system
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: test
        image: mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nats
  name: nats
  namespace: argo-dataflow-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  serviceName: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - command:
        - nats-server
        - --config
        - /etc/nats-config/nats.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).nats.$(POD_NAMESPACE).svc
        image: nats:2.1.7-alpine3.11
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        name: nats
        ports:
        - containerPort: 4222
          hostPort: 0
          name: client
        - containerPort: 7422
          hostPort: 0
          name: leafnodes
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/nats-config
          name: config-volume
        - mountPath: /var/run/nats
          name: pid
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          name: nats-config
        name: config-volume
      - emptyDir: {}
        name: pid
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: stan
  name: stan
  namespace: argo-dataflow-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stan
  serviceName: stan
  template:
    metadata:
      labels:
        app: stan
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - stan
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -sc
        - /etc/stan-config/stan.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nats-streaming:0.16.2
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        name: stan
        ports:
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        volumeMounts:
        - mountPath: /etc/stan-config
          name: config-volume
        - mountPath: /data/stan
          name: stan-sts-vol
      initContainers:
      - args:
        - -fvN
        - nats:8222
        command:
        - curl
        image: golang:1.16
        imagePullPolicy: IfNotPresent
        name: wait
      volumes:
      - configMap:
          name: stan-config
        name: config-volume
  volumeClaimTemplates:
  - metadata:
      name: stan-sts-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: argo-dataflow-system
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 2181
        readinessProbe:
          tcpSocket:
            port: 2181
---
apiVersion: v1
kind: Pod
metadata:
  name: input
  namespace: argo-dataflow-system
spec:
  containers:
  - args:
    - -fvN
    - http://testapi/kafka/pump-topic?topic=input-topic&sleep=2s
    command:
    - curl
    image: golang:1.16
    name: pump-topic
  initContainers:
  - args:
    - -fvN
    - http://testapi/kafka/create-topic?topic=input-topic
    command:
    - curl
    image: golang:1.16
    name: create-input-topic
  - args:
    - -fvN
    - http://testapi/kafka/create-topic?topic=output-topic
    command:
    - curl
    image: golang:1.16
    name: create-output-topic
