apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |-
      This is an example of having multiple replicas for a single step.

      Replicas are automatically scaled up and down depending on the the desired formula, which can be computed using the following:

      * `P` total number of pending messages.
      * `p` change in number of pending messages
      * `c` the current number of replicas.
      * `minmax(v, min, max)` a function to constraint the minimum and maximum number of replicas.

      ### Scale-To-Zero and Peeking

      You can scale to zero by setting `minReplicas: 0`. The number of replicas will start at zero, and periodically be scaled
      to 1  so it can "peek" the the message queue. The number of pending messages is measured and the target number
      of replicas re-calculated.
    dataflow.argoproj.io/owner: argoproj-labs
  name: 103-autoscaling
spec:
  steps:
  - cat: {}
    name: main
    scale:
      desiredReplicas: |
        minmax((c * 256 + p) / 256 + P / (c * 10 * c * 256), 0, 4)
    sinks:
    - kafka:
        topic: output-topic
    sources:
    - kafka:
        topic: input-topic
