apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: "This example uses a HTTP sources and sinks.\n\
      \nHTTP has the advantage that it is stateless and therefore cheap. You not need\
      \ to set-up any storage for your\nmessages between steps. \n\n* A HTTP sink\
      \ may return and error code, clients will need to re-send messages.\n* Adding\
      \ replicas will nearly linearly increase throughput.\n* Due to the lack of state,\
      \ do not use HTTP sources and sinks to connect steps. \n"
    dataflow.argoproj.io/needs: dataflow-103-http-main-source-default-secret.yaml
    dataflow.argoproj.io/owner: argoproj-labs
  name: 301-http
spec:
  steps:
  - cat: {}
    name: cron
    sinks:
    - http:
        url: http://http-main/sources/default
    sources:
    - cron:
        schedule: '*/3 * * * * *'
  - cat: {}
    name: main
    sinks:
    - log: {}
    sources:
    - http:
        serviceName: http-main
