apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named S3 configuration.

      The secret must be named `dataflow-s3-${name}`.
      [Learn about configuration](../docs/CONFIGURATION.md)
  name: dataflow-s3-default
stringData:
  region: us-west-2
  endpoint.url: http://moto:5000
  credentials.accessKeyId.name: dataflow-s3-default
  credentials.accessKeyId.key: accessKeyId
  credentials.secretAccessKey.name: dataflow-s3-default
  credentials.secretAccessKey.key: secretAccessKey
  credentials.sessionToken.name: dataflow-s3-default
  credentials.sessionToken.key: sessionToken
  accessKeyId: admin
  secretAccessKey: password
  sessionToken: ""