apiVersion: v1
kind: Secret
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This is an example of providing a namespace named NATS Streaming configuration.

      The secret must be named `dataflow-jetstream-${name}`.

      [Learn about configuration](../docs/CONFIGURATION.md)
  name: dataflow-jetstream-default
stringData:
  natsUrl: nats-js
  authToken: testingtokentestingtoken
