apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moto
  labels:
    app: moto
spec:
  selector:
    matchLabels:
      app: moto
  template:
    metadata:
      labels:
        app: moto
    spec:
      containers:
        - name: main
          image: motoserver/moto:2.2.4
          ports:
            - containerPort: 5000
          command: [ "/usr/local/bin/moto_server", "-H", "0.0.0.0"]
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 10
  serviceName: moto