apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  template:
    spec:
      containers:
        - name: nats
          ports:
            - containerPort: 4222
              hostPort: 0
            - containerPort: 7422
              hostPort: 0