namespace: argo-dataflow-system
bases:
  - ../crd
  - ../manager
resources:
  - rbac/cluster_role.yaml
  - rbac/cluster_role_binding.yaml
  - ../rbac/leader_election_role.yaml
  - ../rbac/leader_election_role_binding.yaml
  # Comment the following 4 lines if you want to disable
  # the auth proxy (https://github.com/brancz/kube-rbac-proxy)
  # which protects your /metrics endpoint.
  - ../rbac/auth_proxy_service.yaml
  - ../rbac/auth_proxy_role.yaml
  - ../rbac/auth_proxy_role_binding.yaml
  - ../rbac/auth_proxy_client_clusterrole.yaml
  - ../rbac/pipeline-sa.yaml
  - ../rbac/pipeline-role.yaml
  - ../rbac/pipeline-rolebinding.yaml
  - ../base-patch/ssh-configmap.yaml
  - ../base-patch/lead-replica-priorityclass.yaml

patchesStrategicMerge:
  - ../base-patch/manager_auth_proxy_patch.yaml

